name: Release Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    uses: edalzell/github-workflows/.github/workflows/release-publish.yml@ff87c860196291cd1c1f43a45c294ff69df8ee62 # v1.4.0
    permissions:
      contents: write
    secrets:
      release_token: ${{ secrets.RELEASE_TOKEN }}
    with:
      upload_assets: true
