name: Satis

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rebuild-satis:
    name: 'Rebuild Satis Repository'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          curl \
            --fail \
            --silent \
            --show-error \
            --user-agent "Satis-GitHubAction/1.0" \
            --max-time 5 \
            --connect-timeout 5 \
            --request POST \
            --user "${{ secrets.SATIS_TRIGGER_AUTH_USER }}:${{ secrets.SATIS_TRIGGER_AUTH_PASS }}" \
            "${{ secrets.SATIS_TRIGGER_URL }}"
